### ISSUE TITLE
Проблемы с синтаксисом кавычек после конвертации

### ISSUE THREAD

**Issue by DartPower** [PROPHESSOR/Boom2UDMF#1]
![image](https://user-images.githubusercontent.com/2005369/62723906-6bae1e80-ba1a-11e9-9753-478456e8c5ab.png)
Генерируются двойные кавычки, вместо одинарных, после замены на одинарные - гздб успешно открывает карту

**Comment by PROPHESSOR** [comment]
Такс... Посмотрим

**Comment by PROPHESSOR** [comment]
Исправлено
